"""add field resulting_input in EvaluationRule

Revision ID: 3934f66f9054
Revises: 737bde612926
Create Date: 2026-09-22 22:08:58.586868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3934f66f9054'
down_revision: Union[str, Sequence[str], None] = '737bde612926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_rules', sa.Column('resulting_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluation_rules', 'resulting_input')
    # ### end Alembic commands ###
