"""add user_id in tables: action, condition

Revision ID: 9e8c4345f5df
Revises: c55c1f938879
Create Date: 2026-09-23 17:18:53.194582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8c4345f5df'
down_revision: Union[str, Sequence[str], None] = 'c55c1f938879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'actions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('conditions', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'conditions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'conditions', type_='foreignkey')
    op.drop_column('conditions', 'user_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.drop_column('actions', 'user_id')
    # ### end Alembic commands ###
