"""changed relationship rule-action

Revision ID: b5e6806acce9
Revises: 854105eb2eaf
Create Date: 2026-09-22 14:13:19.518210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e6806acce9'
down_revision: Union[str, Sequence[str], None] = '854105eb2eaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('actions_rule_id_key'), 'actions', type_='unique')
    op.drop_constraint(op.f('actions_rule_id_fkey'), 'actions', type_='foreignkey')
    op.drop_column('actions', 'rule_id')
    op.add_column('rules', sa.Column('action_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'rules', 'actions', ['action_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'rules', type_='foreignkey')
    op.drop_column('rules', 'action_id')
    op.add_column('actions', sa.Column('rule_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('actions_rule_id_fkey'), 'actions', 'rules', ['rule_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('actions_rule_id_key'), 'actions', ['rule_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
